--- #YAML:1.0
name:                Tie-Hash-Expire
version:             0.01
abstract:            A tied hash object with key-value pairs that expire.
license:             ~
author:              
    - Colin Wetherbee <cww@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
    Tie::Hash:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
